[project]
name = "nexora-backend"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "JoaoSant7", email = "pedro_romano7@proton.me" }
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "djangorestframework>=3.16.0",
    "drf-spectacular>=0.28.0",
    "django-filter>=25.1",
    "argon2-cffi>=23.1.0",
]

[project.scripts]
nexora-backend = "nexora_backend:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
