# Generated by Django 5.2.18 on 2026-10-07 17:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import starup_backend.profiles.models
import starup_backend.profiles.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestorProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alias",
                    models.CharField(
                        default=starup_backend.profiles.models.generate_alias,
                        editable=False,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StartupProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("website", models.URLField(blank=True)),
                ("category", models.CharField(blank=True, max_length=40)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="startup_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "person_type",
                    models.CharField(
                        choices=[("PF", "Pessoa física"), ("PJ", "Pessoa jurídica")],
                        max_length=2,
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        max_length=14,
                        null=True,
                        unique=True,
                        validators=[
                            starup_backend.profiles.validators.validate_document
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="client_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("document__isnull", True),
                            models.Q(
                                ("document__regex", "^[0-9]{11}$"),
                                ("person_type", "PF"),
                            ),
                            models.Q(
                                ("document__regex", "^[A-Z0-9]{12}[0-9]{2}$"),
                                ("person_type", "PJ"),
                            ),
                            _connector="OR",
                        ),
                        name="client_document_format",
                    )
                ],
            },
        ),
    ]
