# Generated by Django 5.2.18 on 2026-10-07 17:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demands", "0001_initial"),
        ("profiles", "0001_initial"),
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedPost",
            fields=[
                ("position", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DEMAND", "Demanda"),
                            ("REVIEWED_SOLUTION", "Solução avaliada"),
                            ("STARTUP", "Startup"),
                        ],
                        max_length=24,
                    ),
                ),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demand",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="demands.demand",
                    ),
                ),
                (
                    "review",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.review",
                    ),
                ),
                (
                    "startup",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profiles.startupprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-position"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("demand__isnull", False),
                                ("kind", "DEMAND"),
                                ("review__isnull", True),
                                ("startup__isnull", True),
                            ),
                            models.Q(
                                ("demand__isnull", True),
                                ("kind", "REVIEWED_SOLUTION"),
                                ("review__isnull", False),
                                ("startup__isnull", True),
                            ),
                            models.Q(
                                ("demand__isnull", True),
                                ("kind", "STARTUP"),
                                ("review__isnull", True),
                                ("startup__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="feed_exactly_one_target",
                    )
                ],
            },
        ),
    ]
