# Generated by Django 5.2.18 on 2026-10-07 17:16

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("description", models.TextField(max_length=10000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Aberta"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("COMPLETED", "Concluída"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("PUBLIC", "Pública"), ("PRIVATE", "Privada")],
                        default="PUBLIC",
                        max_length=8,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="demands.category",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demands",
                        to="profiles.clientprofile",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"], name="demand_status_created"
                    ),
                    models.Index(
                        fields=["category", "status"], name="demand_category_status"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["OPEN", "IN_PROGRESS", "COMPLETED", "CANCELLED"],
                            )
                        ),
                        name="demand_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("visibility__in", ["PUBLIC", "PRIVATE"])),
                        name="demand_valid_visibility",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("completed_at__isnull", False), ("status", "COMPLETED")
                            ),
                            models.Q(
                                models.Q(("status", "COMPLETED"), _negated=True),
                                ("completed_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="demand_completion_date",
                    ),
                ],
            },
        ),
    ]
