# Generated by Django 6.1.1 on 2026-09-27 14:54

import django.db.models.deletion
import starup_backend.usuarios.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='e-mail')),
                ('password', models.CharField(db_column='senha_hash', max_length=255, verbose_name='senha (hash)')),
                ('nome_civil', models.CharField(max_length=150, verbose_name='nome civil')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='telefone')),
                ('perfil_ativo', models.CharField(choices=[('STARTUP', 'Startup'), ('EMPRESA_CLIENTE', 'Empresa Cliente'), ('INVESTIDOR', 'Investidor'), ('ENTIDADE_FOMENTO', 'Entidade de Fomento'), ('ADMIN', 'Administrador')], max_length=20, verbose_name='perfil ativo')),
                ('termo_privacidade_aceito', models.BooleanField(default=False, verbose_name='termo de privacidade aceito')),
                ('data_aceite_termos', models.DateTimeField(auto_now_add=True, verbose_name='data de aceite dos termos')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'usuario',
                'ordering': ['-criado_em'],
            },
            managers=[
                ('objects', starup_backend.usuarios.models.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='PerfilEmpresaCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=120, verbose_name='razão social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('segmento_operacional', models.CharField(choices=[('OFICINA_MECANICA', 'Oficina Mecânica'), ('MERCADO_VAREJO', 'Mercado / Varejo'), ('DISTRIBUIDORA', 'Distribuidora'), ('RESTAURANTE', 'Restaurante'), ('CLINICA', 'Clínica'), ('LOGISTICA_LOCAL', 'Logística Local'), ('OUTROS', 'Outros')], max_length=20, verbose_name='segmento operacional')),
                ('porte_empresa', models.CharField(choices=[('MEI', 'MEI'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('MEDIO_PORTE', 'Médio Porte')], max_length=15, verbose_name='porte da empresa')),
                ('endereco_cidade_uf', models.CharField(max_length=255, verbose_name='cidade / UF')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_empresa_cliente', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Empresa Cliente',
                'verbose_name_plural': 'Perfis de Empresa Cliente',
                'db_table': 'perfil_empresa_cliente',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilEntidadeFomento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_instituicao', models.CharField(max_length=120, verbose_name='nome da instituição')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('tipo_entidade', models.CharField(choices=[('GRANDE_EMPRESA', 'Grande Empresa'), ('HUB_INOVACAO', 'Hub de Inovação'), ('ACELERADORA', 'Aceleradora'), ('ORGAO_GOVERNO', 'Órgão de Governo'), ('ASSOCIACAO_SETORIAL', 'Associação Setorial')], max_length=20, verbose_name='tipo de entidade')),
                ('site_institucional', models.CharField(blank=True, max_length=100, null=True, verbose_name='site institucional')),
                ('verificado_por_admin', models.BooleanField(default=False, verbose_name='verificado por administrador')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_entidade_fomento', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Entidade de Fomento',
                'verbose_name_plural': 'Perfis de Entidade de Fomento',
                'db_table': 'perfil_entidade_fomento',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilInvestidor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instituicao_origem', models.CharField(blank=True, max_length=120, null=True, verbose_name='instituição de origem')),
                ('cargo_funcao', models.CharField(blank=True, max_length=80, null=True, verbose_name='cargo / função')),
                ('tipo_investidor', models.CharField(choices=[('ANJO', 'Investidor Anjo'), ('PRE_SEED', 'Pré-Seed'), ('SEED', 'Seed'), ('VENTURE_CAPITAL', 'Venture Capital'), ('CORPORATE_VC', 'Corporate VC')], max_length=20, verbose_name='tipo de investidor')),
                ('teses_interesse', models.JSONField(default=list, verbose_name='teses de interesse')),
                ('ticket_medio_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ticket médio mínimo')),
                ('ticket_medio_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='ticket médio máximo')),
                ('confidencialidade_ativa', models.BooleanField(default=True, verbose_name='confidencialidade ativa')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_investidor', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Investidor',
                'verbose_name_plural': 'Perfis de Investidor',
                'db_table': 'perfil_investidor',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PerfilStartup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_startup', models.CharField(max_length=100, verbose_name='nome da startup')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('website', models.CharField(blank=True, max_length=100, null=True, verbose_name='website')),
                ('setor_mercado', models.CharField(choices=[('LOGISTICA', 'Logística'), ('FINANCAS', 'Finanças'), ('VAREJO', 'Varejo'), ('SAUDE', 'Saúde'), ('AGRO', 'Agro'), ('EDUCACAO', 'Educação'), ('SERVICOS', 'Serviços'), ('OUTROS', 'Outros')], max_length=20, verbose_name='setor de mercado')),
                ('estagio_desenvolvimento', models.CharField(choices=[('PROTOTIPO', 'Protótipo'), ('MVP', 'MVP'), ('TRAÇÃO_INICIAL', 'Tração Inicial'), ('ESCALA', 'Escala')], max_length=20, verbose_name='estágio de desenvolvimento')),
                ('pitch_resumido', models.CharField(max_length=300, verbose_name='pitch resumido')),
                ('pontuacao_reputacao', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='pontuação de reputação')),
                ('total_testes_concluidos', models.PositiveIntegerField(default=0, verbose_name='total de testes concluídos')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_startup', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Startup',
                'verbose_name_plural': 'Perfis de Startup',
                'db_table': 'perfil_startup',
                'ordering': ['-criado_em'],
            },
        ),
    ]
