# Generated by Django 5.2.18 on 2026-10-07 17:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("demands", "0001_initial"),
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Solution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("proposal", models.TextField(max_length=10000)),
                ("delivery", models.TextField(blank=True, max_length=10000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Enviada"),
                            ("ACCEPTED", "Aceita"),
                            ("IN_PROGRESS", "Em andamento"),
                            ("DELIVERED", "Entregue"),
                            ("COMPLETED", "Concluída"),
                            ("REJECTED", "Rejeitada"),
                            ("WITHDRAWN", "Retirada"),
                        ],
                        default="SUBMITTED",
                        max_length=16,
                    ),
                ),
                (
                    "demand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solutions",
                        to="demands.demand",
                    ),
                ),
                (
                    "startup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solutions",
                        to="profiles.startupprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SolutionStatusEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("previous_status", models.CharField(blank=True, max_length=16)),
                ("new_status", models.CharField(max_length=16)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="solutions.solution",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="solution",
            index=models.Index(
                fields=["startup", "status"], name="solution_startup_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="solution",
            constraint=models.UniqueConstraint(
                fields=("demand", "startup"), name="one_startup_proposal"
            ),
        ),
        migrations.AddConstraint(
            model_name="solution",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["ACCEPTED", "IN_PROGRESS", "DELIVERED", "COMPLETED"],
                    )
                ),
                fields=("demand",),
                name="one_accepted_solution",
            ),
        ),
        migrations.AddConstraint(
            model_name="solution",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "SUBMITTED",
                            "ACCEPTED",
                            "IN_PROGRESS",
                            "DELIVERED",
                            "COMPLETED",
                            "REJECTED",
                            "WITHDRAWN",
                        ],
                    )
                ),
                name="solution_valid_status",
            ),
        ),
    ]
